### ISSUE TITLE
Build for older platform

### ISSUE THREAD

**Issue by cyber-atomus** [cubehub/demod#3]
This is all nice, kudos for this tool.

I compiled older, C version of demod & all I get is white noise, even with strong FM station.

I can't get Rust version to compile for specific x86 platform, how to do that? Rust seems to compile liquid-dsp on it's own & I need to provide specific --march options. Any help would be nice. Thanks.

**Comment by andresv** [comment]
Hi,

C version is not supported.
Rust can be installed as `curl -sSf https://static.rust-lang.org/rustup.sh | sh`, look here for more details: https://www.rust-lang.org/downloads.html

Liquid-dsp is C library and it must be built as stated in instructions:

```
git clone git://github.com/jgaeddert/liquid-dsp.git
cd liquid-dsp
./bootstrap.sh
./configure
make
sudo make install
```

There are Rust bindings for this lib and they are used automatically by Cargo, look this: https://github.com/cubehub/demod/blob/master/Cargo.toml#L10-L11.

Not sure why you need specific `--march`.

There is also another lib that you might be interested in: https://github.com/simonyiszk/csdr,

**Comment by cyber-atomus** [comment]
Thanks for your reply :)

I need to compile it for AMD Geode CPU.
I already have liquid-dsp build optimized for Geode, and this works with older C code.

The problem is I'm compiling it under 32bit virtual machine (using virtualbox) and cargo/liquid-dsp configure script always tunes liquid-dsp to SSE4 SIMD instructions as the rig is heavy dual Xeon machine. I need to pass to Cargo this option somehow to get proper binary. Setting cflags/cxxflags simply doesn't work.

This is what I need from liquid -> ./configure --enable-simdoverride --enable-fftoverride --with-gcc-arch=geode

My goal is the simplest approach to get raw IQ->doppler correction->demodulate it to FM and your tool is great.
Thanks

**Comment by andresv** [comment]
Well, I guess you are your own with that. I do not know how to do it correctly.
