### ISSUE TITLE
no function or associated item named `new` found

### ISSUE THREAD

**Issue by Kammajaa** [cubehub/demod#4]
Compiling demod v0.9.6 (file:///home/kammajaa/demod)
error[E0599]: no function or associated item named `new` found for type `clap::SubCommand<'_>` in the current scope
   --> src/usage.rs:113:29
    |
113 |                 .subcommand(SubCommand::new("fm")
    |                             ^^^^^^^^^^^^^^^ function or associated item not found in `clap::SubCommand<'_>`

error: aborting due to previous error

error: Could not compile `demod`.

**Comment by andresv** [comment]
I will check it tonight.

**Comment by andresv** [comment]
Fixed.
